apiVersion: v1
kind: ConfigMap
metadata:
  name: nki-mysql-init-configmap-zabbix
  namespace: nki-k8s-monitoring
  labels:
    k8s-app: nki-mysql-server

data:
  init.sh: |
    #!/bin/bash
    set -e
    
    MYSQL_PASSWORD_ZABBIX=$(cat /etc/zabbix/MYSQL_PASSWORD_ZABBIX)
    
    mysql -h localhost -u root -p"${MYSQL_PASSWORD_ZABBIX}" <<EOF
    CREATE DATABASE IF NOT EXISTS zabbix;
    CREATE USER 'zabbix'@'%' IDENTIFIED BY '${MYSQL_PASSWORD_ZABBIX}';
    GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'%';
    FLUSH PRIVILEGES;
    EOF
    chmod +x /init.sh
