apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewfilmes

spec:
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
      - name: reviewfilmes
        image: danncastro/review-filmes:v1
        env:
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgre;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rd2024!"
        ports: 
        - containerPort: 8080

  replicas: 3
  selector:
    matchLabels:
      app: reviewfilmes