apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: danncastro/app-ci-cd:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

  selector:
    matchLabels:
      app: app
