apiVersion: v1
kind: Service
metadata:
  name: front-cluster-ip

spec:
  type: ClusterIP
  selector:
    type: pod-web-server
  ports:
  - name: http
    port: 80
    targetPort: 80
    #targetPort: 8080