apiVersion: v1
kind: Service
metadata:
  name: front-cluster-ip

spec:
  type: ClusterIP
  selector:
    type: pod-web-server
  ports:
  - name: http-apache
    port: 80
    targetPort: 80
  - name: http-tomcat
    port: 8080
    targetPort: 8080