stages:
  - build

build_images:
  stage: build
  image: docker:20.10.16

  services:
  - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

  script:
  - docker build -t danncastro/app-ci-cd:1.0 app/.
  - docker push danncastro/app-ci-cd:1.0