stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
  - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

  script:
  - docker build -t danncastro/app-ci-cd:1.0 app/.
  - docker push danncastro/app-ci-cd:1.0

deploy_gcp:
  stage: deploy_gcp

  before_script:
  - chmod 500 $SSH_KEY

  script:
  - ssh -o StrictHostKeyChecking=no -o $SSH_KEY gcp@SSH_SERVER "sudo rm -Rf ./k8s-pipeline-ci-cd/ && git clone https://gitlab.com/devops-engineer6265823/k8s-pipeline-ci-cd.git && cd k8s-pipeline-ci-cd && sudo chmod +x ./script.sh && ./script.sh"