apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nki-zabbix-server-pvc
  namespace: nki-monitoring
  labels:
    k8s-app: nki-zabbix-server

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: nki-mysql-pv
