apiVersion: v1
kind: PersistentVolume
metadata:
  name: nki-mysql-server-pv
  labels:
    k8s-app: nki-mysql-server

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/mysql/data