apiVersion: apps/v1
kind: ReplicaSet
metadata: #Especificações referentes ao ReplicaSet
  name: replicaset-webserver
  labels: 
    app: frontend
    
spec: 
  template: #Definições referentes ao Pod
    metadata: 
      name: pod-webserver
      labels:
        apps: app-webserver
        tier: frontend
    spec:  #Definições dos containeres que serão executados na Pod
      containers:
      - name: container-nginx
        image: nginx
        
  selector: #Referencia as labels da Pod que será replicado
    matchLabels:
      apps: app-webserver
  replicas: 3