apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  labels:
    type: pod-web-server

spec:
  containers:
  - name: web-server-apache
    image: httpd
    ports:
    - containerPort: 80

  - name: web-server-tomcat
    image: tomcat
    ports:
    - containerPort: 8080