apiVersion: v1
kind: Service
metadata:
  name: front-loadbalancer

spec:
  type: LoadBalancer
  selector:
    type: pod-web-server
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30008