apiVersion: v1
kind: Service
metadata:
  name: nki-zabbix-server-service
  namespace: nki-k8s-monitoring
  labels:
    k8s-app: nki-zabbix-server

spec:
  type: NodePort
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      nodePort: 30006

  selector:
    zabbix-app: nki-zabbix-server
