apiVersion: v1
kind: Service
metadata:
  name: nki-zabbix-server-service
  namespace: nki-k8s-monitoring
  labels:
    k8s-app: nki-zabbix-server

spec:
  type: NodePort
  ports:
    - name: zabbix-server
      port: 10051
      targetPort: 10051
      nodePort: 30051

  selector:
    zabbix-app: nki-zabbix-server
