apiVersion: v1
kind: Pod
metadata:
  name: limits-resources

spec:
  containers:
  - name: apache-container
    image: httpd
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"

  - name: redis-container
    image: redis
    resources:
      requests:
        cpu: "250"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"