apiVersion: v1
kind: Pod
metadata:
  name: volume-hostpath-pod

spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    - name: "hostpath-volume-persistent"
      mountPath: "/datas-persistent"

  volumes:
  - name: "hostpath-volume-persistent"
    hostPath:
      path: "/var/lib/datas-persistent"