apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod

spec:
  containers:
  - name: liveness-container-test
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshould: 3