apiVersion: v1
kind: Pod
metadata:
  name: volume-ephemeral-pod

spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    - name: "cache-storage"
      mountPath: "/volume-test"

  volumes:
  - name: cache-storage
    emptyDir: {}