apiVersion: apps/v1
kind: Deployment
metadata:
  name: nki-mysql-server-deploy
  namespace: nki-k8s-monitoring
  labels:
    k8s-app: nki-mysql-server

spec:
  template:
    metadata:
      name: nki-mysql-server
      labels:
        mysql-app: nki-mysql-server

    spec:
      containers:
      - name: nki-mysql-server
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nki-mysql-server-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: nki-mysql-server-secret
              key: MYSQL_ROOT_USER

        ports:
        - containerPort: 3306

        volumeMounts:
        - name: nki-mysql-persistent-storage
          mountPath: /var/lib/mysql

        - name: nki-init-database-zabbix
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true

        - name: nki-zabbix-mysql-secret-volume
          mountPath: /etc/zabbix
          readOnly: true

      volumes:
      - name: nki-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nki-mysql-server-pvc

      - name: nki-zabbix-mysql-secret-volume
        secret:
          secretName: nki-zabbix-mysql-server-secret

      - name: nki-init-database-zabbix
        configMap:
          name: nki-mysql-init-configmap-zabbix

  selector:
    matchLabels:
      mysql-app: nki-mysql-server