apiVersion: apps/v1
kind: Deployment
metadata:
  name: nki-zabbix-server-deploy
  namespace: nki-monitoring
  labels:
    k8s-app: nki-zabbix-server

spec:
  template:
    metadata:
      name: nki-zabbix-server
      labels:
        zabbix-app: nki-zabbix-server

    spec:
      containers:
      - name: nki-zabbix-server
        image: zabbix/zabbix-server-mysql:latest
        env:
        - name: DB_SERVER_HOST
          value: "nki-mysql-deploy"

        - name: DB_SERVER_PORT
          value: "3306"

        - name: MYSQL_DATABASE
          value: "zabbix"

        - name: MYSQL_USER_ZABBIX
          valueFrom:
            secretKeyRef:
              name: nki-zabbix-secret
              key: MYSQL_USER_ZABBIX

        - name: MYSQL_PASSWORD_ZABBIX
          valueFrom:
            secretKeyRef:
              name: nki-zabbix-secret
              key: MYSQL_PASSWORD_ZABBIX

        ports:
        - containerPort: 10051

        volumeMounts:
        - name: nki-zabbix-server-persistent-data
          mountPath: /usr/share/zabbix

      volumes:
      - name: nki-zabbix-server-persistent-data
        persistentVolumeClaim:
          claimName: nki-mysql-pvc

  replicas: 1
  selector:
    matchLabels:
      zabbix-app: nki-zabbix-server
