name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Login no Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da imgem Docker e envio para o Docker Hub
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: | 
            fabricioveronez/review-filmes:v${{ github.run_number }}
            fabricioveronez/review-filmes:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - name: Configurar as credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Update KubeConfig
      shell: bash
      run: |
        aws eks update-kubeconfig --name imersao-eks --region us-east-1
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deploy.yaml
        images: |
          fabricioveronez/devops4devs-review:${{github.run_number}}