apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nki-mysql-server
  namespace: nki-k8s-monitoring
  labels:
    k8s-app: nki-mysql-server

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
