name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código fonte
      uses: actions/checkout@v4.1.7
      with:
        path: 'k8s-hands-on-testing/k8s-filmes-review'

    - name: Login no Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Passo 1
      run: echo "Deploy aplicação"
